/**
 * The worked-examples gallery.
 *
 * These are complete runs recorded by scripts/build_examples.py and served from
 * the examples/ folder. They exist for two reasons: a demo can show a verified
 * result immediately without waiting on a live run, and the recorded numbers can
 * be compared against what a live run reports. If those disagree, something has
 * regressed.
 *
 * The checkerboard figure is the honest test of alignment and is shown first:
 * craters either run straight across the tile seams or they do not.
 */
import { useEffect, useState } from 'react';
import { X, ExternalLink, AlertTriangle } from 'lucide-react';

import { api } from '../lib/api';

const FIGURES = [
  ['checkerboard', 'Alignment check', 'Alternating tiles from image A warped and image B. Features running straight across the seams mean the registration is right.'],
  ['matches', 'Correspondences', 'Inliers bright, rejected in red. Brightness follows the matcher’s confidence.'],
  ['overlay', 'Overlay', 'A warped onto B, false-coloured. Grey where the two agree; red and cyan fringes are the residual error.'],
  ['keypoints', 'Detections', 'Where the detector found features, independently in each image.'],
  ['residuals', 'Residual field', 'Each inlier drawn where it sits, sized and coloured by its own error.'],
  ['pair', 'Inputs', 'The two tiles as they entered the pipeline.'],
];

export default function Examples({ onClose }) {
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);
  const [selected, setSelected] = useState(null);
  const [figure, setFigure] = useState('checkerboard');
  const [tab, setTab] = useState('runs');

  useEffect(() => {
    api.examples()
      .then((d) => {
        setData(d);
        if (d.examples?.length) setSelected(d.examples[0]);
      })
      .catch((e) => setError(e.message));
  }, []);

  useEffect(() => {
    const onKey = (e) => e.key === 'Escape' && onClose();
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [onClose]);

  const ex = selected;
  const m = ex?.metrics;
  const gt = ex?.ground_truth_error;

  return (
    <div className="ex-backdrop" onClick={(e) => e.target === e.currentTarget && onClose()}>
      <div className="ex-modal">
        <header className="ex-head">
          <div>
            <div className="ex-title">Worked examples</div>
            <div className="ex-sub">
              Recorded runs with their figures. Generated by{' '}
              <code>scripts/build_examples.py</code>
              {data?.generated_utc ? ` · ${data.generated_utc.replace('T', ' ').replace('+00:00', ' UTC')}` : ''}
            </div>
          </div>
          <button className="ex-close" onClick={onClose} title="Close (Esc)"><X size={16} /></button>
        </header>

        {error && (
          <div className="banner" style={{ margin: 16 }}>
            <strong style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 4 }}>
              <AlertTriangle size={13} /> Examples unavailable
            </strong>
            {error}
            <br />
            <span style={{ color: 'var(--text-faint)' }}>
              Run <code>python scripts/build_examples.py</code>.
            </span>
          </div>
        )}

        {data && (
          <div className="ex-switch">
            <button aria-current={tab === 'runs'} onClick={() => setTab('runs')}>
              Recorded runs
            </button>
            <button aria-current={tab === 'proof'} onClick={() => setTab('proof')}>
              Why RMSE is not enough
            </button>
          </div>
        )}

        {data && tab === 'proof' && (
          <div className="ex-proof">
            <p>
              Both detectors run on every scenario where we know the answer. Read the
              last two columns together: reprojection RMSE only says the surviving
              correspondences agree with each other, so a confident fit to the wrong
              correspondences can post an excellent number.
            </p>
            <table className="ex-table">
              <thead>
                <tr>
                  <th>Scenario</th><th>Detector</th><th>Inliers</th>
                  <th>RMSE (px)</th><th>True error (px)</th>
                </tr>
              </thead>
              <tbody>
                {(data.detector_comparison || []).map((r, i) => {
                  const wrong = r.true_error_px != null && r.true_error_px > 50;
                  return (
                    <tr key={i} className={wrong ? 'bad' : ''}>
                      <td>{r.scenario_title}</td>
                      <td>{r.detector}</td>
                      <td className="num">{r.num_inliers}/{r.num_matches}</td>
                      <td className="num">{r.rmse_px.toFixed(3)}</td>
                      <td className="num">
                        {r.true_error_px}
                        {wrong && <span className="ex-flag">wrong</span>}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
            <p className="ex-proof-note">
              The illumination row is the one that matters. SIFT reports the best RMSE
              in the table — 0.138 px — while sitting <strong>821 px</strong> from the
              true transform: under opposed lighting it locks onto five mutually
              consistent but incorrect correspondences and fits them exactly. A pipeline
              reporting only RMSE would call that its best result. This is why the
              interface puts ground-truth error above RMSE wherever it exists, and flags
              a fit with too few inliers as degenerate.
            </p>
          </div>
        )}

        {data && tab === 'runs' && (
          <div className="ex-body">
            <nav className="ex-nav">
              {data.examples.map((e) => (
                <button
                  key={e.id}
                  className="ex-nav-item"
                  aria-current={ex?.id === e.id}
                  onClick={() => setSelected(e)}
                >
                  <div className="ex-nav-top">
                    <span className="ex-nav-name">{e.title}</span>
                    <span className={`tag ${e.provenance.toLowerCase()}`}>{e.provenance}</span>
                  </div>
                  <div className="ex-nav-meta num">
                    {e.metrics.num_inliers}/{e.metrics.num_matches} inliers &middot;{' '}
                    {e.metrics.rmse_px.toFixed(2)} px
                    {e.ground_truth_error
                      ? ` · true ${e.ground_truth_error.mean_corner_error_px.toFixed(2)} px`
                      : ''}
                  </div>
                </button>
              ))}
            </nav>

            {ex && (
              <section className="ex-detail">
                <div className="ex-detail-head">
                  <h3>{ex.title}</h3>
                  <p>{ex.notes}</p>
                </div>

                <dl className="ex-stats">
                  {gt && (
                    <div>
                      <dt>Ground-truth error</dt>
                      <dd style={{ color: 'var(--ok)' }}>
                        {gt.mean_corner_error_px.toFixed(2)} px
                      </dd>
                    </div>
                  )}
                  <div>
                    <dt>Reprojection RMSE</dt>
                    <dd>
                      {m.rmse_px.toFixed(3)} px
                      {m.rmse_m ? ` (${m.rmse_m.toFixed(3)} m)` : ''}
                    </dd>
                  </div>
                  <div>
                    <dt>Inliers</dt>
                    <dd>{m.num_inliers}/{m.num_matches} ({(m.inlier_ratio * 100).toFixed(1)}%)</dd>
                  </div>
                  <div>
                    <dt>Sensors</dt>
                    <dd>{ex.sensor_a} &rarr; {ex.sensor_b}</dd>
                  </div>
                  <div>
                    <dt>Detector</dt>
                    <dd>{ex.detector} + {ex.matcher}</dd>
                  </div>
                  <div>
                    <dt>Ground scale</dt>
                    <dd>{ex.gsd_m} m/px</dd>
                  </div>
                </dl>

                <div className="ex-tabs">
                  {FIGURES.filter(([k]) => ex.figures?.[k]).map(([k, label]) => (
                    <button
                      key={k}
                      className="ex-tab"
                      aria-current={figure === k}
                      onClick={() => setFigure(k)}
                    >
                      {label}
                    </button>
                  ))}
                </div>

                {(() => {
                  const active = FIGURES.find(([k]) => k === figure && ex.figures?.[k])
                    || FIGURES.find(([k]) => ex.figures?.[k]);
                  if (!active) return <div className="ex-empty">No figures for this example.</div>;
                  const [key, label, blurb] = active;
                  return (
                    <>
                      <p className="ex-fig-note">{blurb}</p>
                      <a
                        className="ex-fig"
                        href={ex.figures[key]}
                        target="_blank"
                        rel="noreferrer"
                        title="Open full size"
                      >
                        <img src={ex.figures[key]} alt={`${ex.title} — ${label}`} />
                        <span className="ex-fig-open"><ExternalLink size={12} /> full size</span>
                      </a>
                    </>
                  );
                })()}
              </section>
            )}
          </div>
        )}

        {!data && !error && <div className="ex-empty">Loading examples&hellip;</div>}
      </div>
    </div>
  );
}
